default: diagram all
onlysources.tex := verslag.tex
includes.tex := functies.tex 1_algemeen.tex 2_introductie.tex 3_ontwerp.tex 4_server.tex 5_kiosk.tex 6_invoering.tex

%.eps: %.uxf
	java -jar /usr/share/umlet/umlet.jar -action=convert -format=eps -filename=$<
UXF := $(wildcard diagrammen/*.uxf)
EPS := $(patsubst %.uxf, %.eps, $(UXF))
diagram: 
	$(MAKE) $(EPS)

