default: diagram all
onlysources.tex := verslag.tex
includes.tex := functies.tex 1_algemeen.tex 2_introductie.tex 3_ontwerp.tex 4_server.tex 5_kiosk.tex 6_invoering.tex

%.eps: %.uxf
	java -jar /usr/share/umlet/umlet.jar -action=convert -format=eps -filename=$<
diagram_sources := $(wildcard diagrammen/*.uxf)
diagram_images := $(patsubst %.uxf, %.eps, $(diagram_sources))
diagram: 
	$(MAKE) $(diagram_images)
clean-diagram:
	$(QUIET)$(call clean-files,$(diagram_images))
