default: diagram all
onlysources.tex := verslag-a4.tex
includes.tex := functies.tex 0_begin.tex 1_introductie.tex 2_ontwerp.tex 3_server.tex 4_kiosk.tex 5_interface.tex 6_invoering.tex

%.eps: %.uxf
	java -jar /usr/share/umlet/umlet.jar -action=convert -format=eps -filename=$<
diagram_sources := $(wildcard diagrammen/*.uxf)
diagram_images := $(patsubst %.uxf, %.eps, $(diagram_sources))
diagram: 
	$(MAKE) $(diagram_images)
clean-diagram:
	$(QUIET)$(call clean-files,$(diagram_images))
